#!/usr/bin/env node
/**
 * Bundle esptool-js into a browser ES module.
 *
 * Run only when bumping the esptool-js version; the output is committed so
 * the server never bundles anything at runtime.
 *
 * Usage: node scripts/build-vendor.mjs
 */
import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';

await mkdir('public/vendor', { recursive: true });

await build({
  entryPoints: ['node_modules/esptool-js/lib/index.js'],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  outfile: 'public/vendor/esptool-js.js',
  banner: {
    js: '// Generated by scripts/build-vendor.mjs — do not edit.\n' +
        '// Source: esptool-js (Apache-2.0), https://github.com/espressif/esptool-js\n',
  },
});

console.log('wrote public/vendor/esptool-js.js');
